// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFaAi2mUQi_cWEpoaUMVKsUDOG3maYzC4',
    appId: '1:68726068226:android:46d07e818b00ff7584431b',
    messagingSenderId: '68726068226',
    projectId: 'healthcare-9dd79',
    storageBucket: 'healthcare-9dd79.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM2X2YE9gUhGzfafD3VJmhJDDfQHZcAec',
    appId: '1:68726068226:web:4efa6a2399b4674584431b',
    messagingSenderId: '68726068226',
    projectId: 'healthcare-9dd79',
    authDomain: 'healthcare-9dd79.firebaseapp.com',
    storageBucket: 'healthcare-9dd79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwWCmLEPsN2iKxkDqE1Os09R0qK6doQwk',
    appId: '1:68726068226:ios:6aca95087fa2166184431b',
    messagingSenderId: '68726068226',
    projectId: 'healthcare-9dd79',
    storageBucket: 'healthcare-9dd79.firebasestorage.app',
    androidClientId: '68726068226-2ngco7ptaaf3lfftb3pdc0kll80jtoo0.apps.googleusercontent.com',
    iosClientId: '68726068226-1bc7ucl4plfob3pkd8rijg5aqn48jjf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.graduationProject',
  );

}