import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import 'package:graduation_project/features/booking/domain/entities/medication_item_entity.dart';

class PdfPrescriptionService {
  static Future<void> generatePrescription({
    required String patientName,
    required String doctorName,
    required String diagnosis,
    required List<MedicationItemEntity> items,
  }) async {
    final pdf = pw.Document();
    // ✅ تحميل خط يدعم الـ Unicode (زي Roboto) عشان ميبوظش الـ PDF
    final font = await PdfGoogleFonts.robotoRegular();
    final boldFont = await PdfGoogleFonts.robotoBold();

    pdf.addPage(
      pw.MultiPage(
        theme: pw.ThemeData.withFont(base: font, bold: boldFont),
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            // 1. Header (Logo & Clinic Info)
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      "Wellora Healthcare",
                      style: pw.TextStyle(
                        fontSize: 24,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.purple900,
                      ),
                    ),
                    pw.Text(
                      "Quality Care, Anywhere",
                      style: const pw.TextStyle(
                        fontSize: 12,
                        color: PdfColors.grey700,
                      ),
                    ),
                  ],
                ),
                pw.Text(DateFormat('dd/MM/yyyy').format(DateTime.now())),
              ],
            ),
            pw.Divider(thickness: 2, color: PdfColors.purple900),
            pw.SizedBox(height: 20),

            // 2. Patient & Doctor Info
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                _buildInfoColumn("Patient Name", patientName),
                _buildInfoColumn("Doctor", "Dr. $doctorName"),
              ],
            ),
            pw.SizedBox(height: 20),

            // 3. Diagnosis Section
            pw.Container(
              padding: const pw.EdgeInsets.all(10),
              decoration: const pw.BoxDecoration(color: PdfColors.grey100),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    "Diagnosis:",
                    style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                  ),
                  pw.Text(
                    diagnosis.isEmpty ? "No diagnosis recorded" : diagnosis,
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 30),

            // 4. Medications Table
            pw.Text(
              "Prescribed Medications",
              style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 10),
            pw.TableHelper.fromTextArray(
              border: null,
              headerStyle: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.white,
              ),
              headerDecoration: const pw.BoxDecoration(
                color: PdfColors.purple700,
              ),
              cellHeight: 30,
              cellAlignments: {
                0: pw.Alignment.centerLeft,
                1: pw.Alignment.center,
                2: pw.Alignment.center,
              },
              headerPadding: const pw.EdgeInsets.all(5),
              cellPadding: const pw.EdgeInsets.all(5),
              headers: ['Medication', 'Dosage', 'Frequency'],
              data:
                  items
                      .map(
                        (item) => [
                          item.medicationName,
                          item.dosage,
                          item.frequency,
                        ],
                      )
                      .toList(),
            ),

            pw.Spacer(),
            // 5. Footer (Signature & Instructions)
            pw.Divider(),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  "Generated by Wellora App",
                  style: const pw.TextStyle(
                    fontSize: 10,
                    color: PdfColors.grey,
                  ),
                ),
                pw.Column(
                  children: [
                    pw.Container(
                      width: 100,
                      decoration: const pw.BoxDecoration(
                        border: const pw.Border(bottom: pw.BorderSide()),
                      ),
                    ),
                    pw.Text(
                      "Doctor's Signature",
                      style: const pw.TextStyle(fontSize: 10),
                    ),
                  ],
                ),
              ],
            ),
          ];
        },
      ),
    );

    // عرض الـ Preview للمستخدم عشان يطبع أو يحمل
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
    );
  }

  static pw.Widget _buildInfoColumn(String label, String value) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          "$label:",
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
        ),
        pw.Text(
          value,
          style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
        ),
      ],
    );
  }
}
